### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by liamxg** [milos-agathon/mapping-river-basins-with-r#2]
python main.py 
Traceback (most recent call last):
  File "/Users/lixingguang/Desktop/amazing/milos-agathon/mapping-river-basins-with-r/py/main.py", line 187, in <module>
    with open('py/api-key.txt', "r") as apikeyfile:
FileNotFoundError: [Errno 2] No such file or directory: 'py/api-key.txt'

**Comment by liamxg** [comment]
@milos-agathon

**Comment by liamxg** [comment]
<img width="432" alt="image" src="https://github.com/milos-agathon/mapping-river-basins-with-r/assets/46078579/d05c1adb-9624-4e98-881e-97040e487ad1">

**Comment by liamxg** [comment]
any comments on this?

**Comment by milos-agathon** [comment]
Hello, I will remove the python file from my repo because it was created by another user and I merged it into my master. But I can't maintain it because I use R and not Python

**Comment by liamxg** [comment]
@milos-agathon I also use R and not Python.

**Comment by milos-agathon** [comment]
Sorry, but I don't understand your comment. I see you created a map of China's river basins. Can you be more precise?

**Comment by liamxg** [comment]
any comments on China map that I created, so I can improve it, thanks.
